# Generated by Django 4.0.3 on 2022-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capproject', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='platform',
        ),
        migrations.AddField(
            model_name='product',
            name='platform_site',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
